version: '2'
services:
  web:
    depends_on:
     - db
    build: './'
    ports:
     - "8080:8080"
    command: >
      bash -c "go run main.go"
    env_file:
      - 'variables.env'
    volumes:
      - ./:/mooncascade-task
  db:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./mounts/db_data:/var/lib/postgresql/data
    env_file:
      - 'variables.env'